### ISSUE TITLE
I think I need to use htmlDependencies

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/user2016format#1]
Hi @yihui,

This is way too last minute, and I can just show the custom functions that do not use css (like html_doc_0 and html_doc_1) - but could you point me in the right direction?

For example, when I use html_doc_2: https://github.com/ijlyttle/user2016docdemo/blob/master/R/html_doc_2.R

This is similar to the example shown here: http://rmarkdown.rstudio.com/developer_custom_formats.html

It works ok "interactively", but the css file (comic_sans.css) does not get copied into the `_site` directory when I build the site.

Looking at https://github.com/rstudio/bookdown/blob/master/R/gitbook.R, I see that you are doing something more to establish an htmlDependency, but I'm stuck has to how to proceed.

Can you point me in the right direction? It will be ok if we don't have this for the tutorial.

Thanks,

Ian

**Comment by yihui** [comment]
You can pass a `htmlDependency()` to the `extra_dependencies` argument of `html_document`.

**Comment by ijlyttle** [comment]
Hi @yihui -

My brain is starting to return to me, so I have had a chance to look at this a little more.

What I want to have happen is outlined by this [commented-out code](https://github.com/ijlyttle/user2016docdemo/blob/master/R/html_doc_4.R#L40-L48)

What I have (almost) working is mostly implemented [here](https://github.com/ijlyttle/user2016docdemo/blob/master/R/html_doc_4.R#L50-L66)

Using `htmlDependency()`, the files are copied into `site_libs` and there are links made in the rendered html file to the css files. Great!

The problem is the order. The custom css I specify gets overruled by the theme, etc. I think [this is the code](https://github.com/rstudio/rmarkdown/blob/master/R/html_document_base.R#L83-L95) where that happens.

Here's the [Rmd I run it on](https://raw.githubusercontent.com/ijlyttle/user2016_knitr/master/Part2/3_roll_your_own/roll_your_own.Rmd) 

Questions:
1. Is there something I can do to change the order of the dependencies being added?
2. If not, could [this](https://github.com/rstudio/rmarkdown/blob/master/R/html_document_base.R#L83-L95) be changed to add "custom" dependencies last? I imagine there may a reason you all did this using this order, but I thought I'd ask. If so, I'll take the issue there.
3. Of course, I could be doing something dumb...

Thanks as always,

Ian

**Comment by yihui** [comment]
I think it makes more sense to add `extra_dependencies` _after_ the Bootstrap theme dependencies, so you may either file an issue to rmarkdown or put together a pull request to switch the order of these two types of dependencies.

**Comment by ijlyttle** [comment]
Thanks! Will do.

**Comment by ijlyttle** [comment]
got it sorted out! Looks to be in R Markdown 1.1
